name: AI Bundle — Pack (wip)

on:
  workflow_dispatch:
    inputs:
      filter:
        description: 'Regex to filter filenames (e.g., "receipt|checkup")'
        required: false
        default: ''
      root:
        description: 'Folder containing .sql files'
        required: false
        default: 'patches'
      pr_paths:
        description: 'PR対象パス（例: patches/receipt/**, patches/checkup/**）'
        required: false
        default: ''

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: wip              # ← wip をチェックアウト

      - uses: actions/setup-python@v5
        with: { python-version: '3.x' }

      - name: Pack bundle from wip
        id: pack
        run: |
          chmod +x scripts/pack_ai_bundle.py || true
          ts=$(date +%Y%m%d_%H%M%S)
          out="ai_out/ai_bundle_${ts}.txt"
          mkdir -p ai_out
          cmd="python3 scripts/pack_ai_bundle.py --root '${{ github.event.inputs.root }}' --out '${out}'"
          if [ -n "${{ github.event.inputs.filter }}" ]; then
            cmd="$cmd --filter '${{ github.event.inputs.filter }}'"
          fi
          if [ -n "${{ github.event.inputs.pr_paths }}" ]; then
            cmd="$cmd --pr-paths '${{ github.event.inputs.pr_paths }}'"
          fi
          eval "$cmd"
          echo "outfile=${out}" >> $GITHUB_OUTPUT

      - name: Commit to wip (mobile friendly)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ai_out/
          git commit -m "AI bundle (wip): add $(basename '${{ steps.pack.outputs.outfile }}')" || echo "no changes"
          git push origin HEAD:wip

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: ai_bundle_wip
          path: ${{ steps.pack.outputs.outfile }}
