name: Generate README by Scan (manual)

on:
  # 手動のみ
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Python version'
        required: false
        default: '3.x'
      script_path:
        description: 'Scanner script path'
        required: false
        default: 'scripts/gen_readme_scan.py'
      extra_args:
        description: 'Extra args for the script (optional)'
        required: false
        default: ''
      commit:
        description: 'Commit README.md if changed? (true/false)'
        required: false
        default: 'true'

jobs:
  build-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # READMEをコミットするため

    steps:
      # 「Run workflow」で選んだブランチに対して実行
      - name: Checkout selected branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Run scanner
        shell: bash
        run: |
          set -e
          if [ ! -f "${{ inputs.script_path }}" ]; then
            echo "Scanner not found: ${{ inputs.script_path }}"
            exit 1
          fi
          python3 "${{ inputs.script_path }}" ${{ inputs.extra_args }}

      - name: Commit README.md if changed
        if: ${{ inputs.commit == 'true' }}
        shell: bash
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md || true
          git commit -m "README auto-update by scan" || echo "no changes"
          git push

      # コミットしない場合は成果物で確認できるようにする（任意）
      - name: Upload README artifact (when commit=false)
        if: ${{ inputs.commit != 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: README-preview
          path: README.md
          if-no-files-found: ignore
